server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yummy?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

yummy-system:
  min-payment: 0.01
  pay-time: 15
  activating-link: localhost/activate/
  super-manager:
    id: root
    #123456
    password: 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92

lbs:
  key: HYVBZ-QI7C5-EBFIA-QJMEN-DAVT2-S7B4Q

smtp:
  key: goulheucygtrbjci
  email: 260386109@qq.com